apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: AL2
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "${aws_eks_cluster.cluster.name}"
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "${aws_eks_cluster.cluster.name}"
  role: "Karpenter-eksspotworkshop"
  tags:
    Name: karpenter.sh/nodepool/default
    NodeType: "karpenter-workshop"
    IntentLabel: "apps"
