---
# Source: knative-helm-chart/templates/service.yaml
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello-a
  namespace: hello-world
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
    spec:
      containers:
        - image: 767397668494.dkr.ecr.us-east-1.amazonaws.com/ngnix-knative:1.2.1
          ports:
            - containerPort: 80
          name: ngnix
          envFrom:
            - secretRef:
                name: secret-to-be-created
          env:
            - name: SERVICE
              value: "http://syncron.com"
      imagePullSecrets:
        - name: ecr-secret
---
# Source: knative-helm-chart/templates/namespace.yaml
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: hello-world
#   labels:
#     name: hello-world
---
# Source: knative-helm-chart/templates/domainmapping.yaml
apiVersion: networking.internal.knative.dev/v1alpha1
kind: ClusterDomainClaim
metadata:
  name: abc.767397668494.realhandsonlabs.net
spec:
  namespace: hello-world
---
# Source: knative-helm-chart/templates/domainmapping.yaml
apiVersion: serving.knative.dev/v1beta1
kind: DomainMapping
metadata:
  name: abc.767397668494.realhandsonlabs.net
  namespace: hello-world
spec:
  ref:
    name: hello-1
    kind: Service
    apiVersion: serving.knative.dev/v1