apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: k8s-external-secret
#  namespace: helloworld  # Add namespace if required
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: k8s-native-external-secret
    kind: ClusterSecretStore
  target:
    name: secret-to-be-created
    creationPolicy: Owner
  data:
    - secretKey: mysql_pass
      remoteRef:
        key: rds-password
        property: password
