apiVersion: v1
kind: Namespace
metadata:
  name: hello-world
  labels:
    name: hello-world
---
apiVersion: networking.internal.knative.dev/v1alpha1
kind: ClusterDomainClaim
metadata:
  name: python.992382557570.realhandsonlabs.net
spec:
  namespace: hello-world

---
apiVersion: serving.knative.dev/v1beta1
kind: DomainMapping
metadata:
  name: python.992382557570.realhandsonlabs.net
  namespace: hello-world
spec:
  ref:
    name: hello
    kind: Service
    apiVersion: serving.knative.dev/v1
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello
  namespace: hello-world
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
    spec:
      containers:
        - image: stacksimplify/kubenginx:1.0.0
          ports:
            - containerPort: 80

