namespace: "hello-world"

domain:
  name: test.891377368990.realhandsonlabs.net

knativeService:
  name: hello
  image: ""
  minScale: 1
  serviceEnv:
    SERVICE_URL: "http://syncron.com"

ingress:
  name: test-alb-2
  ingressClass: alb
  scheme: internet-facing
  certificateArn: "" # Populated dynamically via Terraform
  targetService: istio-ingressgateway
  targetPort: 80

aws:
  region: us-east-1

externalSecrets:
  rdsPasswordKey: "" # Populated dynamically via Terraform
