namespace: "hello-world"

domain:
  name: test.654654326569.realhandsonlabs.net

knativeService:
  name: hello
  image: ""
  minScale: 1
  serviceEnv:
    SERVICE_URL: "http://syncron.com"

# ingress:
#   name: test-alb-2
#   ingressClass: alb
#   scheme: internet-facing
#   certificateArn: "" # Populated dynamically via Terraform
#   targetService: istio-ingressgateway
#   targetPort: 80

externalSecrets:
  rdsPasswordKey: "" # Populated dynamically via Terraform

## ecr external secret
aws:
  region: us-east-1
  ecrSecretKey: ecr-secret-key

clusterSecretStore:
  name: ecr-secret-store
  serviceAccountName: external-ecr-sa

ecr:
  host: 654654326569.dkr.ecr.us-east-1.amazonaws.com
  password: stdin
externalSecret:
  name: ecr-token-secret
  refreshInterval: 5h
  targetSecretName: ecr-docker-secret
iamRoleArn: arn:aws:iam::123456789012:role/your-role

