namespace: "helloworld"

domain:
  name: world.975050194088.realhandsonlabs.net

knativeService:
  name: hello
  image: 975050194088.dkr.ecr.us-east-1.amazonaws.com/ngnix-knative:1.2.1
  minScale: 1
  serviceEnv:
    SERVICE_URL: "http://syncron.com"

ingress:
  name: test-alb
  ingressClass: alb
  scheme: internet-facing
  certificateArn: "" # Populated dynamically via Terraform
  targetService: istio-ingressgateway
  targetPort: 80

aws:
  region: us-east-1

externalSecrets:
  rdsPasswordKey: "rds-password-key" # Populated dynamically via Terraform
