apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: k8s-native-external-secret
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.aws.region }}
      auth:
        jwt:
          serviceAccountRef:
            name: schema-registry-service-account
            namespace: {{ .Values.namespace }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: k8s-external-secret
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: k8s-native-external-secret
    kind: ClusterSecretStore
  target:
    name: secret-to-be-created
    creationPolicy: Owner
  data:
    - secretKey: mysql_pass
      remoteRef:
        key: {{ .Values.externalSecrets.rdsPasswordKey }}
        property: password