apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.clusterSecretStore.serviceAccountName }}
  namespace: {{ .Values.namespace }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.iamRoleArn }}

---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.clusterSecretStore.name }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.aws.region }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.clusterSecretStore.serviceAccountName }}
            namespace: {{ .Values.namespace }}

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecret.name }}
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.clusterSecretStore.name }}
    kind: ClusterSecretStore
  target:
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: '{"auths":{"{{ .Values.ecr.host }}":{"username":"AWS","password":"{{ .Values.ecr.password }}","auth":"{{ printf "%s:%s" "AWS" .Values.ecr.password | b64enc }}"}}}'
    name: {{ .Values.externalSecret.targetSecretName }}
  data:
    - secretKey: ecr.password
      remoteRef:
        key: {{ .Values.aws.ecrSecretKey }}
