apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: k8s-native-external-secret
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: schema-registry-service-account
            namespace: helloworld

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: k8s-external-secret
  namespace: helloworld  # Ensure the namespace is correct
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: k8s-native-external-secret
    kind: ClusterSecretStore
  target:
    name: secret-to-be-created
    creationPolicy: Owner
  data:
    - secretKey: mysql_pass
      remoteRef:
        key: rds-password
        property: password
