apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: default
  namespace: karpenter
  labels:
    app.kubernetes.io/app: Karpenter
spec:
  amiFamily: AL2
  instanceProfile: KarpenterNodeInstanceProfileus-east-1
  subnetSelectorTerms:
    - tags:
       kubernetes.io/role/internal-elb: "1"
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: vpc-0569fcc43db1f3b18-us-east-1-dev-security-group
  tags:
    karpenter.sh/discovery: csx-services-compute-dev-us-east-1
  blockDeviceMappings:
  - deviceName: '/dev/xvda'
    rootVolume: true
    ebs:
      encrypted: false
      volumeType: gp3
      volumeSize: 20Gi