---
# Source: knative-helm-chart/templates/service.yaml
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello
  namespace: hello-world
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
    spec:
      containers:
        - image: "590184049425.dkr.ecr.us-east-1.amazonaws.com/ngnix-knative:1.2.1"
          ports:
            - containerPort: 80
          name: ngnix
          envFrom:
            - secretRef:
                name: secret-to-be-created
          env:
            - name: SERVICE
              value: "http://syncron.com"
      imagePullSecrets:
        - name: ecr-registry-secret
---
# Source: knative-helm-chart/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-alb-2
  namespace: istio-system
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/certificate-arn: 
    alb.ingress.kubernetes.io/target-type: ip
spec:
  rules:
  - http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: istio-ingressgateway
              port:
                number: 80
---
# Source: knative-helm-chart/templates/namespace.yaml
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: hello-world
#   labels:
#     name: hello-world
---
# Source: knative-helm-chart/templates/domainmapping.yaml
apiVersion: networking.internal.knative.dev/v1alpha1
kind: ClusterDomainClaim
metadata:
  name: test.590184049425.realhandsonlabs.net
spec:
  namespace: hello-world
---
# Source: knative-helm-chart/templates/external-secrets.yaml
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: k8s-native-external-secret
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: schema-registry-service-account
            namespace: hello-world
---
# Source: knative-helm-chart/templates/domainmapping.yaml
apiVersion: serving.knative.dev/v1beta1
kind: DomainMapping
metadata:
  name: test.590184049425.realhandsonlabs.net
  namespace: hello-world
spec:
  ref:
    name: hello
    kind: Service
    apiVersion: serving.knative.dev/v1
---
# Source: knative-helm-chart/templates/external-secrets.yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: k8s-external-secret
  namespace: hello-world  # Ensure the namespace is correct
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: k8s-native-external-secret
    kind: ClusterSecretStore
  target:
    name: secret-to-be-created
    creationPolicy: Owner
  data:
    - secretKey: mysql_pass
      remoteRef:
        key: rds-password
        property: password
