apiVersion: v1
kind: Namespace
metadata:
  name: helloworld
  labels:
    name: helloworld
---
apiVersion: networking.internal.knative.dev/v1alpha1
kind: ClusterDomainClaim
metadata:
  name: 767397963763.realhandsonlabs.net
spec:
  namespace: helloworld

