apiVersion: v1
kind: Namespace
metadata:
  name: helloworld
  labels:
    name: helloworld
---
apiVersion: networking.internal.knative.dev/v1alpha1
kind: ClusterDomainClaim
metadata:
  name: world.905418218028.realhandsonlabs.net
spec:
  namespace: helloworld

---
apiVersion: serving.knative.dev/v1beta1
kind: DomainMapping
metadata:
  name: world.905418218028.realhandsonlabs.net
  namespace: helloworld
spec:
  ref:
    name: hello
    kind: Service
    apiVersion: serving.knative.dev/v1
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello
  namespace: helloworld
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
    spec:
      containers:
        - image: stacksimplify/kubenginx:1.0.0
          ports:
            - containerPort: 80
          env:
            - name: SERVICE
              value: "http://syncron.com"


