apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-ingress
  namespace: helloworld
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/subnets: subnet-00fb5aee1319c44c0, subnet-07441e15ba9e454a6
    alb.ingress.kubernetes.io/security-groups: sg-0111e598a9a13bc1c
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:211125293311:certificate/5e9ee287-98b7-4b4e-85f6-09be5e172508
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port
  labels:
    app: hello-ingress
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: istio-ingressgateway
                port:
                  number: 80
