apiVersion: serving.knative.dev/v1beta1
kind: DomainMapping
metadata:
  name: hello.905418229946.realhandsonlabs.net
  namespace: helloworld
spec:
  ref:
    name: hello
    kind: Service
    apiVersion: serving.knative.dev/v1
  # tls:
  #   secretName: <cert-secret>