apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: infra-api
  namespace: istio-ingress
  labels:
    dl_app: infra-api
    environment: dev
  annotations:
    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:us-east-1:339713068874:certificate/7d53c80f-be26-4a68-a29d-c87b164caf4d"
    alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=300
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: instance
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: istio-ingressgateway
                port:
                  number: 80