apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets
  namespace: helloworld
spec:
  provider: aws
  parameters:
    objects: |
        - objectName: "rds-password"
          objectType: "secretsmanager"