namespace: hello-world

domain:
  name: world.471112941965.realhandsonlabs.net

knativeService:
  name: hello
  image: stacksimplify/kubenginx:1.0.0
  minScale: 1
  serviceEnv:
    SERVICE_URL: "http://syncron.com"

ingress:
  name: test-alb
  ingressClass: alb
  scheme: internet-facing
  certificateArn: "" # This will be populated dynamically via Terraform
  targetService: istio-ingressgateway
  targetPort: 80
