name: 'schema-app-deployment'

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
          
    - name: Install aws-cli dependencies
      run: |
        python -m pip install --upgrade pip
        pip install awscli

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-east-1
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: List S3 buckets
      run: |
        aws s3 ls
    
    - name: setup Kubectl
      id: install-Kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: "v1.30.0"    

    - name: Configure kubectl and print nodes output
      run: |
        aws eks update-kubeconfig --region us-east-1 --name demo
        kubectl get nodes

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.5.5"

    - name: List files in schema directory
      run: ls -al schema

    - name: Terraform Initialize
      working-directory: schema
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: terraform init

    - name: Terraform Validate
      working-directory: schema
      run: terraform validate

    - name: Terraform Plan
      working-directory: eks-addons
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: terraform plan

    - name: Terraform Apply
      working-directory: eks-addons
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: terraform apply -auto-approve