name: 'Terraform'

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Cosign
      uses: sigstore/cosign-installer@v3.5.0
      with:
        cosign-release: "v2.2.4"
    - name: Check Cosgin install!
      run: cosign version
## Disable in first deployment
    - name: setup Kubectl
      id: install-Kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: "v1.30.0"
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
          
    - name: Install aws-cli dependencies
      run: |
        python -m pip install --upgrade pip
        pip install awscli

    - name: Configure AWS Credentials 2
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-east-1
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: listing s3 buckets
      run: |
        aws s3 ls

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.5.5"

    - name: Terraform Initialize
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: terraform init
      
#    - name: List S3 Buckets
      # env:
      #   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      # run: |
      #   aws s3 ls

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: terraform plan

    - name: Terraform Apply
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: terraform apply -auto-approve

    - name: setup Kubectl
      id: install-Kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: "v1.30.0"

    - name: Configure kubectl and printing nodes output
      run: |
        aws eks update-kubeconfig --region us-east-1 --name demo
        kubectl get nodes
